### ISSUE TITLE
Send internal telemetry to related outgoing relations

### ISSUE THREAD

**Issue by MichaelThamm** [canonical/opentelemetry-collector-k8s-operator#15]
### Enhancement Proposal

According to [internal-telemetry](https://opentelemetry.io/docs/collector/internal-telemetry) we can configure the internal telemetry. We should configure this for `logs` and `metrics` so that we actually send this to the receiving relation, e.g. Loki for logs and Prometheus for metrics.

I am not sure if we can specify arbitrary exporter configs here in the internal telemetry section, would be good to investigate.

## Forward internal logs
```yaml
service:
  telemetry:
    logs:
      level: INFO
      processors:
        - batch:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: https://backend:4318
```

## Forward internal metrics
```yaml
service:
  telemetry:
    level: normal
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888
```
Not sure what the difference is between exporting internal metrics like in the example above verses (what we currently do):
```yaml
  # Data sources: metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 5s
          static_configs:
            - targets: [localhost:8888]
```
Where we ingest the internal metrics from `0.0.0.0:8888/metrics`. It seems that the first example is cleaner, since the output and input definition is in the internal telemetry section and not spread throughout the config sections.
