### ISSUE TITLE
Add TLS functionality

### ISSUE THREAD

**Issue by MichaelThamm** [canonical/opentelemetry-collector-k8s-operator#9]
### Enhancement Proposal

There are a few locations where we need to consider [TLS in otelcol](https://opentelemetry.io/docs/specs/semconv/attributes-registry/tls/) which often requires certs defined in the config file:

```yaml
        tls:
          cert_file: cert.pem
          key_file: cert-key.pem
```

- [ ] Scan the source code in the charm for "http"
